version: '2'

services:
  megashop-assets-service:
    container_name: megashop-assets-service
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # volumes:
    #   - .:/wwww/var
    ports:
      - "8045:${PORT}"
    expose:
      - 8045
    networks:
      - megashop
networks:
  megashop:
    driver: bridge
