version: '2'

services:
  recipe-service:
    container_name: recipe-service
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes: 
      - .:/var/www
    ports:
      - "8080:3000"
    depends_on:
      - mongo
    networks:
      - recipe_network

  mongo:
    container_name: mongo
    image: mongo
    networks:
      - recipe_network
networks:
  recipe_network:
    driver: bridge
